spring.application.name=tarefas

# Conexao com o banco H2 em memoria
spring.datasource.url=jdbc:h2:mem:tarefasdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Liga o console web do H2, acessivel em /h2-console
spring.h2.console.enabled=true

# Mostra no log o SQL que o Hibernate gera (bom para aprender)
spring.jpa.show-sql=true

# Cria/atualiza as tabelas automaticamente com base nas Entities
spring.jpa.hibernate.ddl-auto=update
